/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#004ac6",
        "secondary-container": "#fd761a",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-container": "#ffede6",
        "outline-variant": "#c3c6d7",
        "on-secondary-container": "#5c2400",
        "on-secondary-fixed": "#341100",
        "surface-bright": "#f9f9ff",
        "background": "#f9f9ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#7d2d00",
        "secondary-fixed-dim": "#ffb690",
        "tertiary": "#943700",
        "error": "#ba1a1a",
        "inverse-on-surface": "#edf0ff",
        "on-secondary-fixed-variant": "#783200",
        "surface-container-low": "#f1f3ff",
        "surface-variant": "#dce2f7",
        "primary-fixed": "#dbe1ff",
        "on-background": "#141b2b",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "outline": "#737686",
        "tertiary-fixed": "#ffdbcd",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dce2f7",
        "on-primary-fixed": "#00174b",
        "surface-container": "#e9edff",
        "surface": "#f9f9ff",
        "surface-dim": "#d3daef",
        "inverse-surface": "#293040",
        "error-container": "#ffdad6",
        "inverse-primary": "#b4c5ff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "on-tertiary": "#ffffff",
        "on-surface": "#141b2b",
        "tertiary-container": "#bc4800",
        "secondary": "#9d4300",
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#434655",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-high": "#e1e8fd",
        "secondary-fixed": "#ffdbca"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
